// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure.DataContext;

namespace Normative_Calculator.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Img_Url")
                        .IsRequired()
                        .HasMaxLength(1020)
                        .HasColumnType("character varying(1020)")
                        .HasColumnName("img_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Created_Date = new DateTime(2010, 1, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://media.istockphoto.com/photos/heap-of-bread-picture-id995038782?k=20&m=995038782&s=612x612&w=0&h=40HBdtHiBgOESo870LBOgc6xUt1E3bqhOhqPCXZTNbc=",
                            Name = "Bread"
                        },
                        new
                        {
                            Id = 3,
                            Created_Date = new DateTime(2005, 2, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://simply-delicious-food.com/wp-content/uploads/2018/10/breakfast-board.jpg",
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 4,
                            Created_Date = new DateTime(2015, 3, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://funcakes.com/content/uploads/2021/02/Red-Velvet-Cake-with-Fruit-960x720-c-default.jpg",
                            Name = "Cake"
                        },
                        new
                        {
                            Id = 5,
                            Created_Date = new DateTime(2018, 4, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://images.theconversation.com/files/439369/original/file-20220104-19-12kg47e.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=900.0&fit=crop",
                            Name = "Candy"
                        },
                        new
                        {
                            Id = 6,
                            Created_Date = new DateTime(2020, 5, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://assets.bonappetit.com/photos/5f809c81ba63e7584fca0576/8:5/w_1800,h_1125,c_limit/Double-Garlic-Roast-Chicken-With-Onion-Gravy.jpg",
                            Name = "Chicken"
                        },
                        new
                        {
                            Id = 7,
                            Created_Date = new DateTime(2021, 6, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://static.onecms.io/wp-content/uploads/sites/23/2020/06/23/italian-food-2000.jpg",
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 8,
                            Created_Date = new DateTime(2010, 7, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://saladswithanastasia.com/wp-content/uploads/2021/12/radish-green-salad-land1.jpg",
                            Name = "Salad"
                        },
                        new
                        {
                            Id = 9,
                            Created_Date = new DateTime(2012, 8, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://www.thespruceeats.com/thmb/MbHAC6HNO7rjkZXA_GwHvbQ46EA=/2000x1500/smart/filters:no_upscale()/basic-cherry-pie-recipe-995136-14-dfe79487adf64a848a49dd07983b6614.jpg",
                            Name = "Pie"
                        },
                        new
                        {
                            Id = 10,
                            Created_Date = new DateTime(2000, 9, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://insidr.co/wp-content/uploads/2018/04/Boeuf-Bourguignon-1170x780-2.jpg",
                            Name = "French"
                        },
                        new
                        {
                            Id = 11,
                            Created_Date = new DateTime(2001, 10, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://www.healthyeating.org/images/default-source/home-0.0/nutrition-topics-2.0/general-nutrition-wellness/2-2-2-3foodgroups_fruits_detailfeature.jpg?sfvrsn=64942d53_4",
                            Name = "Fruit"
                        },
                        new
                        {
                            Id = 12,
                            Created_Date = new DateTime(2002, 11, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://www.thoughtco.com/thmb/F5IEThuihsz_k-ptOUx1SP4KJoI=/2119x1192/smart/filters:no_upscale()/chopped-pork-meat-cooked-with-red-chili-paste--gochujang-sauce--over-rice-690784532-5c8bd3dc46e0fb000146acf1.jpg",
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 13,
                            Created_Date = new DateTime(2003, 12, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://www.thespruceeats.com/thmb/TTsydZkvlx25nvMQPZq0wB5o87c=/1500x1500/smart/filters:no_upscale()/GettyImages-1042998066-518ca1d7f2804eb09039e9e42e91667c.jpg",
                            Name = "Thai"
                        },
                        new
                        {
                            Id = 14,
                            Created_Date = new DateTime(2005, 1, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://post.healthline.com/wp-content/uploads/2020/09/vegetarian-diet-plan-732x549-thumbnail.jpg",
                            Name = "Vegetarian"
                        },
                        new
                        {
                            Id = 15,
                            Created_Date = new DateTime(2016, 6, 2, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://food-images.files.bbci.co.uk/food/recipes/chickensoup_1918_16x9.jpg",
                            Name = "Soup"
                        },
                        new
                        {
                            Id = 16,
                            Created_Date = new DateTime(2015, 3, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://media.istockphoto.com/photos/seafood-platter-grilled-lobster-shrimps-scallops-langoustines-octopus-picture-id1305699663?k=20&m=1305699663&s=612x612&w=0&h=x1FHZSXT9H8ttwoD6oDtBKB19QQdDml9ZmY_sZqHuNc=",
                            Name = "Seafood"
                        },
                        new
                        {
                            Id = 17,
                            Created_Date = new DateTime(2014, 5, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://static.toiimg.com/thumb/83740315.cms?width=1200&height=900",
                            Name = "Sandwich"
                        },
                        new
                        {
                            Id = 18,
                            Created_Date = new DateTime(2000, 3, 1, 7, 47, 0, 0, DateTimeKind.Unspecified),
                            Img_Url = "https://img.taste.com.au/sv9d9AM6/w720-h480-cfill-q80/taste/2016/11/pork-and-bean-burrito-bowl-109208-1.jpeg",
                            Name = "Lunch"
                        });
                });

            modelBuilder.Entity("backend.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Lowest_Measure_Unit_Price")
                        .HasColumnType("double precision")
                        .HasColumnName("lowest_measure_unit_price");

                    b.Property<int>("Measure_Unit")
                        .HasColumnType("integer")
                        .HasColumnName("measure_unit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("name");

                    b.Property<int>("Purchase_Measure_Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("purchase_measure_quantity");

                    b.Property<double>("Purchase_Price")
                        .HasMaxLength(30)
                        .HasColumnType("double precision")
                        .HasColumnName("purchase_price");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.ToTable("ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Lowest_Measure_Unit_Price = 0.0015,
                            Measure_Unit = 3,
                            Name = "Ulje",
                            Purchase_Measure_Quantity = 1,
                            Purchase_Price = 1.5
                        },
                        new
                        {
                            Id = 2,
                            Lowest_Measure_Unit_Price = 0.00080000000000000004,
                            Measure_Unit = 3,
                            Name = "Mlijeko",
                            Purchase_Measure_Quantity = 1,
                            Purchase_Price = 0.80000000000000004
                        },
                        new
                        {
                            Id = 3,
                            Lowest_Measure_Unit_Price = 0.001,
                            Measure_Unit = 3,
                            Name = "Voda",
                            Purchase_Measure_Quantity = 1,
                            Purchase_Price = 1.0
                        },
                        new
                        {
                            Id = 4,
                            Lowest_Measure_Unit_Price = 0.002,
                            Measure_Unit = 0,
                            Name = "Brasno",
                            Purchase_Measure_Quantity = 1,
                            Purchase_Price = 2.0
                        },
                        new
                        {
                            Id = 5,
                            Lowest_Measure_Unit_Price = 0.0030000000000000001,
                            Measure_Unit = 0,
                            Name = "Mljeveno meso",
                            Purchase_Measure_Quantity = 1,
                            Purchase_Price = 3.0
                        },
                        new
                        {
                            Id = 6,
                            Lowest_Measure_Unit_Price = 0.0023,
                            Measure_Unit = 0,
                            Name = "Tjestenina",
                            Purchase_Measure_Quantity = 1,
                            Purchase_Price = 2.2999999999999998
                        });
                });

            modelBuilder.Entity("backend.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Category_Id")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1020)
                        .HasColumnType("character varying(1020)")
                        .HasColumnName("description");

                    b.Property<string>("Img_Url")
                        .IsRequired()
                        .HasMaxLength(1020)
                        .HasColumnType("character varying(1020)")
                        .HasColumnName("img_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("character varying(127)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("Category_Id")
                        .HasDatabaseName("ix_recipes_category_id");

                    b.ToTable("recipes");
                });

            modelBuilder.Entity("backend.Models.RecipesIngredients", b =>
                {
                    b.Property<int>("Ingredient_Id")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("Recipe_Id")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Recipe_Measure_Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_measure_quantity");

                    b.Property<int>("Recipe_Measure_Unit")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_measure_unit");

                    b.HasKey("Ingredient_Id", "Recipe_Id")
                        .HasName("pk_recipe_ingredients");

                    b.HasIndex("Recipe_Id")
                        .HasDatabaseName("ix_recipe_ingredients_recipe_id");

                    b.ToTable("recipe_ingredients");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte[]>("Password_Has")
                        .HasColumnType("bytea")
                        .HasColumnName("password_has");

                    b.Property<byte[]>("Password_Salt")
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("backend.Models.Recipe", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("Category_Id")
                        .HasConstraintName("fk_recipes_categories_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend.Models.RecipesIngredients", b =>
                {
                    b.HasOne("backend.Models.Ingredient", "Ingredient")
                        .WithMany("Recipes_Ingredients")
                        .HasForeignKey("Ingredient_Id")
                        .HasConstraintName("fk_recipe_ingredients_ingredients_ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Recipe", "Recipe")
                        .WithMany("Recipes_Ingredients")
                        .HasForeignKey("Recipe_Id")
                        .HasConstraintName("fk_recipe_ingredients_recipes_recipe_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("backend.Models.Ingredient", b =>
                {
                    b.Navigation("Recipes_Ingredients");
                });

            modelBuilder.Entity("backend.Models.Recipe", b =>
                {
                    b.Navigation("Recipes_Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
